version: "3.9"
services:
  postgresql:
    container_name: postgres
    image: postgres:13.1
    environment:
      - POSTGRES_DB=schedule_management
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    restart: always
    ports:
      - 5432:5432/tcp
